name: Build and upload release artifacts

on:
  release:
    types: [published]

jobs:
  build-and-release:
    permissions:
      contents: write # to upload release assets

    strategy:
      matrix:
        runner:
          - name: linux-amd64
            runs-on: ubuntu-24.04
            goos: linux
            goarch: amd64

          - name: linux-arm64
            runs-on: ubuntu-24.04-arm
            goos: linux
            goarch: arm64

    env:
      ARTIFACT_NAME: "inference-snaps-cli-${{ matrix.runner.name }}.tar.xz"

    runs-on: ${{ matrix.runner.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26.x'

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.runner.goos }}
          GOARCH: ${{ matrix.runner.goarch }}
        run: |
          go build -ldflags="-s -w" -o ./modelctl ./cmd/modelctl

      - name: Generate artifact
        run: |
          # Organize files
          mkdir -p bin
          mv ./modelctl ./bin/modelctl
          mv ./completer/snap.bash ./bin/snap-completer.bash

          # Create archive
          tar -Jcvf ${{ env.ARTIFACT_NAME }} \
            ./bin/modelctl \
            ./bin/snap-completer.bash \
            ./LICENSE

      - name: Upload release asset
        run: |
          # --clobber overwrites existing assets of the same name
          gh release upload ${{ github.event.release.tag_name }} ${{ env.ARTIFACT_NAME }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
