name: Snap CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

env:
  SNAP_NAME: stack-utils

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26.x'

      - name: Run tests
        run: go test -v ./...

  build:
    needs: [ test ]
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      # Upload snap with components
      # Adapted from https://github.com/canonical/inference-snaps-dev/blob/f744b98984a29c377b61d3f7141df79cbad1f67d/.github/workflows/build-publish-snap.yaml#L54-L86
      - name: Publish snap
        if: github.ref == 'refs/heads/main'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}  
          CHANNEL: latest/edge
        run: |
          channel="${{ env.CHANNEL }}"
          echo -e "Channel:\n\t$channel"

          snap_file="$(ls *.snap)"
          snap_size=$(du -h "$snap_file" | cut -f1)
          echo -e "Snap file:\n\t$snap_file $snap_size"

          # Build components argument list
          component_args=()
          echo "Snap components:"
          for comp_file in *.comp; do
              comp_size=$(du -h "$comp_file" | cut -f1)

              # Component file name patterns:
              # <snap_name>+<comp_name>_<comp_version>.comp
              # <snap_name>+<comp_name>.comp
              comp_name=$(echo "$comp_file" | 
                  cut -d'+' -f2 | # drop snap name
                  cut -d'.' -f1 | # drop file extension
                  cut -d'_' -f1) # split by _, take 1st part

              echo -e "\t$comp_file $comp_size"

              component_args+=(--component "$comp_name=$comp_file")
          done

          echo -e "\nUploading snap..."
          set -x
          snapcraft upload "$snap_file" "${component_args[@]}" --release="$channel"
